### ISSUE TITLE
add premium client functionality

### ISSUE THREAD

**Issue by Japoivvb** [Dynavy/SHOP-PROJECT#1]
1. before ask for client name in sale option, include a new question about if the client is premium or not.

-    if the answer is No, continue flow as is

-    if the answer is Yes, 

       create a premiumClient object which extends from Client, 
	   it has a points attribute and its pay method is the same as parent client but for each 10€ sales, it adds 1 point. e.g. if sale 35€, premiumClient gets 3 points.
       show its points earned after the sale total amount
	   
2. set issue label as enhancement to be tracked

3. commit message with verb + #numberIssue + details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by Dynavy** [comment]
Issue fixed and code pushed to main branch.

Commit: 

![image](https://github.com/Dynavy/UF4P1-M03/assets/159908255/c8ddaec0-c24d-4d9c-b324-2d7e0ac12231)

Code changes: 

![image](https://github.com/Dynavy/UF4P1-M03/assets/159908255/eb0624e6-c160-4335-8113-e94cdb40c550)

Example of a premium client that spends a total of 30€ on sales:

![image](https://github.com/Dynavy/UF4P1-M03/assets/159908255/1f0fdd3a-47d3-49a2-8a2f-56c1c80c79af)

**Comment by Japoivvb** [comment]
1. ok
2. ok
3. ok
4. ok
5. ok
great job, you got +1 in UF4P1
